<a href="https://colab.research.google.com/github/bachi-mohamed-rafik/numpy-learning/blob/main/Numpy_training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy 

In [1]:
import pandas as pd
import numpy as np

In [2]:
#numpy version and the configuration 
print(np.__version__)
print(np.show_config())


1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


In [3]:
#3. Create a null vector of size 10 
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#4. How to find the memory size of any array
print(x.itemsize)


8


In [6]:
#6. Create a null vector of size 10 but the fifth value which is 1
y=np.zeros(10)
y[4]=1
print(y)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
#7. Create a vector with values ranging from 10 to 49 
s=np.arange(10,49)
print(s)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [8]:
#8. Reverse a vector (first element becomes last)
b=s[::-1]
print("reversed list",b)

reversed list [48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [9]:
#9. Create a 3x3 matrix with values ranging from 0 to 8
m=np.arange(0,9).reshape(3,3)
print(m)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0] 
f=[1,2,0,0,4,0]
out_tpl = np.nonzero(f)
print(out_tpl)

(array([0, 1, 4]),)


In [11]:
#11. Create a 3x3 identity matrix
im=np.identity(3)
print(im)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
#12. Create a 3x3x3 array with random values
print("Create a 3x3x3 array with random values")
a=np.random.random((3,3,3))
print(a)

Create a 3x3x3 array with random values
[[[0.29030964 0.91391091 0.98952707]
  [0.99375975 0.11579927 0.01376291]
  [0.08871514 0.77408718 0.60783213]]

 [[0.46718619 0.32933815 0.24731996]
  [0.80688669 0.00600869 0.30999148]
  [0.81288039 0.98939895 0.13022311]]

 [[0.98518238 0.04622329 0.14574683]
  [0.13787928 0.95117871 0.0978088 ]
  [0.30093919 0.55642791 0.98596819]]]


In [13]:
#Create a 10x10 array with random values and find the minimum and maximum values
print("Create a 10x10 array with random values and find the minimum and maximum values :")
c=np.random.random((10,10))
mi=c.min()
ma=c.max()
print("min",mi)
print("max",ma)

Create a 10x10 array with random values and find the minimum and maximum values :
min 0.014743935031925726
max 0.9963202481049771


In [14]:
#14. Create a random vector of size 30 and find the mean value 
rv=np.random.random(30)
print(rv)

[0.68102938 0.46911272 0.9516751  0.20273528 0.67861411 0.68856281
 0.11854601 0.68146343 0.32659728 0.99650106 0.58127651 0.4466422
 0.92339551 0.31998302 0.39608612 0.18114911 0.69526805 0.45204358
 0.93426599 0.11533233 0.82609071 0.07395185 0.64056341 0.44253196
 0.63492254 0.47446323 0.07871792 0.79135438 0.33714203 0.77886899]


In [16]:
#15. Create a 2d array with 1 on the border and 0 inside
j=np.ones((5,5))
j[1:-1,1:-1]=0
print(j)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
#16. How to add a border (filled with 0's) around an existing array? 
t=np.ones((4,4))
print("The original array")
print(t)
t=np.pad(t,pad_width=1,mode='constant',constant_values=0)
print(t)

The original array
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [18]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
print("18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal:")

Z = np.diag(1+np.arange(4),k=-1)
print(Z)

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal:
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [19]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern
print("Create a 8x8 matrix and fill it with a checkerboard pattern:")
n=np.zeros((8,8))
n[1::2,::2] = 1
n[::2,1::2] = 1
print(n)

Create a 8x8 matrix and fill it with a checkerboard pattern:
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [20]:
#20. the index (x,y,z) of the 100th element
print("the index (x,y,z) of the 100th element:")
print(np.unravel_index(99,(6,7,8)))

the index (x,y,z) of the 100th element:
(1, 5, 3)


In [21]:
#21. Create a checkerboard 8x8 matrix using the tile function 
print("Create a checkerboard 8x8 matrix using the tile function :")
n = 8
arr = ([0,1])
print(np.tile(arr,(n,n//2)))

Create a checkerboard 8x8 matrix using the tile function :
[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


In [22]:
#22Normalize a 5x5 random matrix
print("Normalize a 5x5 random matrix:")
x=np.random.random((5,5))
xmax,xmin=x.max(),x.min()
x=(x-xmin)/(xmax-xmin)
print(x)

Normalize a 5x5 random matrix:
[[0.03937513 0.52325638 0.98837489 0.11143559 0.5529144 ]
 [0.23040284 0.91911762 0.53633165 0.94579507 0.99545813]
 [0.72214523 0.12778637 0.49640042 0.38963804 0.76682196]
 [1.         0.45772603 0.91840391 0.56086484 0.36455401]
 [0.35345886 0.71319693 0.14204452 0.90428997 0.        ]]


In [23]:
#23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) 
print("Create a custom dtype that describes a color as four unsigned bytes (RGBA) :")
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

Create a custom dtype that describes a color as four unsigned bytes (RGBA) :
[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


In [24]:
#24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
print("Multiply a 5x3 matrix by a 3x2 matrix:")
a=np.random.random((5,3))
b=np.random.random((3,2))
print(a.dot(b))

Multiply a 5x3 matrix by a 3x2 matrix:
[[0.48541138 0.8789778 ]
 [0.9425049  1.34182759]
 [0.12292369 0.51449881]
 [0.48013125 1.0649029 ]
 [0.12047063 0.1684405 ]]


In [25]:
#25. Given a 1D array, negate all elements which are between 3 and 8, in place.
print("Given a 1D array, negate all elements which are between 3 and 8, in place:")
arr=np.arange(11)
print(arr)
m = (arr > 3) & (arr < 8)
arr[m] *= -1
print(arr)

Given a 1D array, negate all elements which are between 3 and 8, in place:
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [26]:
#29. How to round away from zero a float array 
print("Round away from zero a float array :")
a=[0,1,2,4,57,8,5.5,2]
np.round(a,0)
print(a)

Round away from zero a float array :
[0, 1, 2, 4, 57, 8, 5.5, 2]


In [27]:
#30. How to find common values between two arrays?
print("Find common values between two arrays:")
a=np.array([1,2,3])
b=np.array([1,2,4])
c=np.intersect1d(a,b)
print(c)

Find common values between two arrays:
[1 2]


In [28]:
#33. How to get the dates of yesterday, today and tomorrow?
print("How to get the dates of yesterday, today and tomorrow:")
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
print("yesterday :",yesterday)

today=np.datetime64('today','D')
print("today:",today)

tommorow=np.datetime64('today','D')+np.timedelta64(1,'D')
print("tommorow :",tommorow)

How to get the dates of yesterday, today and tomorrow:
yesterday : 2020-12-17
today: 2020-12-18
tommorow : 2020-12-19


In [29]:
#34. How to get all the dates corresponding to the month of July 2016? 
print("Get all the dates corresponding to the month of July 2016 :")
print(np.arange('2016-07','2016-08',dtype='datetime64[D]'))

Get all the dates corresponding to the month of July 2016 :
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [30]:
#35. How to compute ((A+B)*(-A/2)) in place (without copy)? 
print("Compute ((A+B)*(-A/2)) in place (without copy):")
a=np.ones(3)
b=np.ones(3)
np.add(a,b,out=b)
np.divide(a,2,out=a)
np.negative(a,out=a)
np.multiply(a,b,out=a)
print(a)


Compute ((A+B)*(-A/2)) in place (without copy):
[-1. -1. -1.]


In [31]:
#36. Extract the integer part of a random array of positive numbers using 4 different methods 
print("Extract the integer part of a random array of positive numbers :")
e=np.random.uniform(0,10,10)
print(e)
print(e.astype(int))

Extract the integer part of a random array of positive numbers :
[0.73340311 3.18967845 7.91439899 9.20867003 0.39675584 4.94840934
 3.69219877 4.16806931 7.93857805 2.76641773]
[0 3 7 9 0 4 3 4 7 2]


In [32]:
#37. Create a 5x5 matrix with row values ranging from 0 to 4
print("Create a 5x5 matrix with row values ranging from 0 to 4:")
u=np.zeros((5,5))
u+=np.arange(5)
print(u)

Create a 5x5 matrix with row values ranging from 0 to 4:
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [33]:
#38. Consider a generator function that generates 10 integers and use it to build an array
print("Consider a generator function that generates 10 integers and use it to build an array:")
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

Consider a generator function that generates 10 integers and use it to build an array:
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [34]:
#39. Create a vector of size 10 with values ranging from 0 to 1, both excluded
print("Create a vector of size 10 with values ranging from 0 to 1, both excluded:")
x = np.linspace(0,1,12,endpoint=True)[1:-1]
print(x)

Create a vector of size 10 with values ranging from 0 to 1, both excluded:
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [35]:
#40. Create a random vector of size 10 and sort it 
print("Create a random vector of size 10 and sort it :")
x=np.random.random(10)
x.sort()
print(x)

Create a random vector of size 10 and sort it :
[0.38510633 0.41504303 0.57865401 0.61858813 0.66231301 0.76004882
 0.83922802 0.85171698 0.90729684 0.96012033]


In [36]:
#41. How to sum a small array
print("Sum a small array")
c=np.arange(10)
print(np.sum(c))

Sum a small array
45


In [37]:
#42. Consider two random array A and B, check if they are equal 
A=np.random.randint(0,2,10)
print(A)
B=np.random.randint(0,2,10)
print(B)
e=np.allclose(A,B)
print(e)

[1 0 0 0 1 0 0 1 0 0]
[0 0 0 1 1 0 0 0 1 1]
False


In [38]:
#43. Make an array immutable 
print("Make an array immutable ")
A.flags.writeable=False

Make an array immutable 


In [39]:
#44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
print("Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates:")
z= np.random.random((10,2))
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates:
[0.62565235 0.47204513 0.57984355 0.85632953 0.54307907 0.99386628
 0.83996979 0.64134242 0.95361437 0.27729654]
[1.46337067 0.22081922 0.89826544 1.32046833 1.23371832 0.48592438
 1.36306815 0.58855929 0.23107683 0.67906711]


In [40]:
#45. Create random vector of size 10 and replace the maximum value by 0
print("Create random vector of size 10 and replace the maximum value by 0:")
t= np.random.random((10))
print(t)
t[t.argmax()] = 0
print(t)

Create random vector of size 10 and replace the maximum value by 0:
[0.78002261 0.12156865 0.60331438 0.63471534 0.55064957 0.52580114
 0.18359057 0.88330238 0.08904084 0.33219701]
[0.78002261 0.12156865 0.60331438 0.63471534 0.55064957 0.52580114
 0.18359057 0.         0.08904084 0.33219701]


In [41]:
#47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))


print("Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))")
x= np.array([1,2,3])
print(x)
y= np.array([1,5,4])
print(y)

x = x.reshape((-1,1))
print(x)
diff_matrix = x-y
print(diff_matrix)
cauchym = 1.0/diff_matrix
print(cauchym)

Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
[1 2 3]
[1 5 4]
[[1]
 [2]
 [3]]
[[ 0 -4 -3]
 [ 1 -3 -2]
 [ 2 -2 -1]]
[[        inf -0.25       -0.33333333]
 [ 1.         -0.33333333 -0.5       ]
 [ 0.5        -0.5        -1.        ]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:14: RuntimeWarning: divide by zero encountered in true_divide
  


In [42]:
#48. Print the minimum and maximum 
print("Minimum and maximum :")
print(np.max(x))
print(np.min(x))

Minimum and maximum :
3
1


In [43]:
#49. How to print all the values of an array? 
print("Print all the values of an array:")
x= np.array([1,2,3])
for i in x:
	print(i,end=' ')

Print all the values of an array:
1 2 3 

In [44]:
#50. How to find the closest value (to a given scalar) in a vector?
print("find the closest value (to a given scalar) in a vector:")
x=np.arange(100)
print("The original array:")
print(x)
a=np.random.uniform(0,100)
print("Value to compare :")
print(a)
indx=(np.abs(x-a)).argmin()
print(indx)

find the closest value (to a given scalar) in a vector:
The original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Value to compare :
48.230016641374064
48


In [45]:
#Create a structured array representing a position (x,y) and a color (r,g,b)
print("Create a structured array representing a position (x,y) and a color (r,g,b):")
Z = np.zeros(10, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', float),
                                  ('g', float),
                                  ('b', float)])])
print(Z)

Create a structured array representing a position (x,y) and a color (r,g,b):
[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [46]:
#52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances
print("Consider a random vector with shape (100,2) representing coordinates, find point by point distances:")
rv=np.random.rand(100,2)
print(rv)

Consider a random vector with shape (100,2) representing coordinates, find point by point distances:
[[1.28870725e-01 7.23755748e-01]
 [7.55722203e-01 9.82355065e-01]
 [8.33638412e-01 5.91463056e-01]
 [7.98861719e-01 4.64231737e-01]
 [8.09741941e-02 6.11249707e-01]
 [8.07991987e-01 4.96646050e-01]
 [5.46794883e-02 2.01474359e-01]
 [4.63656255e-01 2.12203117e-01]
 [2.19138299e-01 6.66881910e-01]
 [6.76539661e-01 1.71430236e-01]
 [5.65185990e-01 1.34168697e-01]
 [1.92507332e-01 6.45883824e-01]
 [5.94555768e-01 3.91279844e-01]
 [8.60263651e-01 4.34446446e-01]
 [8.14420428e-01 5.56720661e-01]
 [6.40024327e-01 7.44246786e-01]
 [2.25479653e-01 7.65790890e-01]
 [8.44343174e-01 6.64609922e-02]
 [9.73282729e-01 3.46810592e-01]
 [6.44608898e-01 6.07955274e-01]
 [4.91557229e-01 4.32813387e-01]
 [8.32224881e-01 2.70705278e-01]
 [9.22486302e-01 1.82618204e-01]
 [5.64027986e-01 5.45130090e-02]
 [6.18372350e-01 7.69554474e-01]
 [3.77926502e-01 6.30487776e-01]
 [7.07680868e-01 1.75192194e-01]
 [3.0081