<a href="https://colab.research.google.com/github/bachi-mohamed-rafik/nympy-learning/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy


import libraray


In [ ]:
import numpy as np


# scalar



In [ ]:
x=np.array(7)
print("x=",x)
print("number of dimensions of x:", x.ndim)
print("Dimensions", x.shape)
print("size of scalar x:",x.size)
print("The type of x:",x.dtype)

x= 7
number of dimensions of x: 0
Dimensions ()
size of scalar x: 1
The type of x: int64


#Vector

In [ ]:
v=np.array([1.2,4.5,7.8])
print("The vector v :",v)
print("number of dimensions of v:", v.ndim)
print("Dimensions", v.shape)
print("size of scalar v:",v.size)
print("The type of v:",v.dtype)

The vector v : [1.2 4.5 7.8]
number of dimensions of v: 1
Dimensions (3,)
size of scalar v: 3
The type of v: float64


#Matrix


In [ ]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("The x matrix:\n",x)
print("number of dimensions of x:", x.ndim)
print("Dimensions", x.shape)
print("size of scalar x:",x.size)
print("The type of x:",x.dtype)

The x matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
number of dimensions of x: 2
Dimensions (3, 3)
size of scalar x: 9
The type of x: int64


#3-D Tensor


In [ ]:
x=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(x)
print("count of dimensions :",x.ndim)
print("Dimensions :",x.shape)
print("The size of x :",x.size)
print("The type of x :",x.dtype)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
count of dimensions : 3
Dimensions : (2, 2, 2)
The size of x : 8
The type of x : int64


#Functions creation

In [ ]:
print("np.zeros((2,2))",np.zeros((2,2)))
print("np.ones((2,2)):\n",np.ones((2,2)))
print("np.eye((2,2)):\n",np.eye((2)))
print("np.random.random((2,2))\n",np.random.random((2,2)))
print("np.random.randint((2,2))\n",np.random.randint((3,3,3)))

np.zeros((2,2)) [[0. 0.]
 [0. 0.]]
np.ones((2,2)):
 [[1. 1.]
 [1. 1.]]
np.eye((2,2)):
 [[1. 0.]
 [0. 1.]]
np.random.random((2,2))
 [[0.42788655 0.19633381]
 [0.72771463 0.29036027]]
np.random.randint((2,2))
 [2 0 2]


#Indexing

In [ ]:
#indexing
x=np.array([1,2,5,7,8,8])
print("x=",x)
print("the second element of x:",x[1])



x= [1 2 5 7 8 8]
the second element of x: 2


In [ ]:
#slicing
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("x matrix:\n",x)
print("x column 2 \n:",x[:,1])
print("x row 3 \n:",x[2,:])
print("x rows 0,1 & cols 1,2:\n",x[0:2,1:3])

x matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
x column 2 
: [2 5 8]
x row 3 
: [7 8 9]
x rows 0,1 & cols 1,2:
 [[2 3]
 [5 6]]


In [ ]:
#integer array indexing
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(x)
rg=np.array([1,3,2])
cg=np.array([0,2,2])
print("indxed values:",x[rg,cg])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
indxed values: [ 4 12  9]


In [ ]:
#Boolean array indexing
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,22,44]])
print(x)
print("x<5\n",x<5)
print("x[x>5]",x[x>5])


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 22 44]]
x<5
 [[ True  True  True]
 [ True False False]
 [False False False]
 [False False False]]
x[x>5] [ 6  7  8  9 10 22 44]


In [ ]:
#Arithmetic
x=np.array([[1,2],[2,5],[7,8]])
print("x:\n",x)
y=np.array([[2,5],[8,7],[9,6]])
print("y:\n",y)
print("x+y:\n",np.add(x,y))
print("x-y :\n",np.subtract(x,y))
print("x*y :\n",np.multiply(x,y))

x:
 [[1 2]
 [2 5]
 [7 8]]
y:
 [[2 5]
 [8 7]
 [9 6]]
x+y:
 [[ 3  7]
 [10 12]
 [16 14]]
x-y :
 [[-1 -3]
 [-6 -2]
 [-2  2]]
x*y :
 [[ 2 10]
 [16 35]
 [63 48]]


In [ ]:
#Dot product
a=np.array([[1,2],[2,5],[5,8]],dtype=np.float64)
b=np.array([[1,2,4],[2,5,4]],dtype=np.float64)
c=a.dot(b)
print(a.shape ,"*",b.shape,"=",c.shape)
print("c=\n",c)

(3, 2) * (2, 3) = (3, 3)
c=
 [[ 5. 12. 12.]
 [12. 29. 28.]
 [21. 50. 52.]]


In [ ]:
#Axis operations
x=np.array([[1,2],[5,4]])
print("x=\n",x)
print("sum all :\n ",np.sum(x))
print("sum by rows :\n ",np.sum(x, axis=0))
print("sum by columns :\n ",np.sum(x, axis=1))

x=
 [[1 2]
 [5 4]]
sum all :
  12
sum by rows :
  [6 6]
sum by columns :
  [3 9]


In [ ]:
#Min/Max
a=np.array([[1,2,3],[5,6,4]])
print("a:\n",a)
print("min of a: ",x.min())
print("max of a: ",x.max())
print("min x index 0 \n",x.min(axis=0))
print("min x index 1 \n",x.min(axis=1))

a:
 [[1 2 3]
 [5 6 4]]
min of a:  1
max of a:  5
min x index 0 
 [1 2]
min x index 1 
 [1 4]


In [ ]:
# Broadcasting
a=np.array([[2,4],[2,4]])
b=np.array([5,4])
print("a+b=\n",a+b)
c=np.array([5])
print("b+c=\n",b+c)

a+b=
 [[7 8]
 [7 8]]
b+c=
 [10  9]


In [ ]:
#Transposing
w=np.array([[1,2,3],[5,4,4],[4,5,99],[88,45,0]])
print("w=\n",w)
print(w.shape)
wt=np.transpose(w)
print("w transpose\n",wt)
print(wt.shape)

w=
 [[ 1  2  3]
 [ 5  4  4]
 [ 4  5 99]
 [88 45  0]]
(4, 3)
w transpose
 [[ 1  5  4 88]
 [ 2  4  5 45]
 [ 3  4 99  0]]
(3, 4)


In [ ]:
#Reshaping
s=np.array([1,2,57,5,5,4])
print("s=\n",s)  
t=np.reshape(s,(2,3))
print("t=\n",t)
c=np.reshape(s,(3,-1))
print("c=\n",c)

s=
 [ 1  2 57  5  5  4]
t=
 [[ 1  2 57]
 [ 5  5  4]]
c=
 [[ 1  2]
 [57  5]
 [ 5  4]]


In [ ]:
#Adding removing dimensions
#Adding
x = np.array([[[1,2,3]],[[4,5,6]]])
print("x= \n",x)
print("x dimension:\n",x.shape)
c=np.expand_dims(x,1)
print("c=\n",c)
print("c dimension:\n",c.shape)
#Removing
y = np.squeeze(x, 1) # squeeze dim 1
print ("y: \n", y)
print ("y.shape: ", y.shape)  # notice extra set of brackets are gone

x= 
 [[[1 2 3]]

 [[4 5 6]]]
x dimension:
 (2, 1, 3)
c=
 [[[[1 2 3]]]


 [[[4 5 6]]]]
c dimension:
 (2, 1, 1, 3)
y: 
 [[1 2 3]
 [4 5 6]]
y.shape:  (2, 3)
